services:
  - type: web
    name: katarik
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: katarik-rooms
            property: connectionString
      - key: ALLOWED_ORIGINS
        value: https://katarik-5g25.onrender.com,https://localhost,capacitor://localhost

  - type: keyvalue
    name: katarik-rooms
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction
